import { Platform, StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const authColors = {
  background: 'transparent',
  card: 'rgba(255, 248, 239, 0.12)',
  cardBorder: 'rgba(255, 248, 239, 0.16)',
  surface: 'rgba(255, 248, 239, 0.12)',
  primary: colors.green,
  primarySoft: 'rgba(255, 248, 239, 0.12)',
  text: colors.cream,
  muted: 'rgba(255, 248, 239, 0.78)',
  hint: 'rgba(255, 248, 239, 0.58)',
  white: colors.white,
};

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: authColors.background,
    direction: 'rtl',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 32,
    gap: 16,
    direction: 'rtl',
  },
  hero: {
    paddingTop: 20,
    gap: 6,
    direction: 'rtl',
    alignItems: 'flex-end',
  },
  eyebrow: {
    color: colors.gold,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 12,
    textAlign: 'left',
    writingDirection: 'rtl',
    alignSelf: 'flex-start',
  },
  title: {
    color: authColors.text,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 24,
    textAlign: 'left',
    writingDirection: 'rtl',
    lineHeight: 38,
    alignSelf: 'stretch',
    width: '100%',
  },
  subtitle: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    fontSize: 14,
    textAlign: 'left',
    writingDirection: 'rtl',
    lineHeight: 24,
    alignSelf: 'stretch',
    width: '100%',
  },
  card: {
    backgroundColor: authColors.card,
    borderColor: authColors.cardBorder,
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 12,
    shadowColor: colors.greenDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: Platform.OS === 'android' ? 2 : 0,
    direction: 'rtl',
    alignItems: 'stretch',
  },
  sectionTitle: {
    color: colors.gold,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 14,
    textAlign: 'right',
    writingDirection: 'rtl',
    alignSelf: 'flex-start',
  },
  sectionHint: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
    lineHeight: 22,
    alignSelf: 'stretch',
    width: '100%',
  },
  field: {
    backgroundColor: authColors.surface,
    borderColor: authColors.cardBorder,
    borderRadius: 16,
    borderWidth: 1,
    color: colors.cream,
    paddingHorizontal: 14,
    paddingVertical: 14,
    textAlign: 'right',
    writingDirection: 'rtl',
    direction: 'rtl',
  },
  optionCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    direction: 'rtl',
  },
  optionTitle: {
    color: colors.gold,
    fontFamily: 'NotoKufiArabic-Bold',
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  optionDescription: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'right',
    writingDirection: 'rtl',
    lineHeight: 22,
    alignSelf: 'stretch',
    width: '100%',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.gold,
    borderRadius: 16,
    paddingVertical: 15,
    shadowColor: colors.green,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: Platform.OS === 'android' ? 2 : 0,
    direction: 'rtl',
  },
  primaryButtonText: {
    color: colors.greenDarker,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 15,
  },
  centerText: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'center',
    writingDirection: 'rtl',
    lineHeight: 24,
  },
  actionLink: {
    alignItems: 'center',
  },
  actionLinkText: {
    color: colors.gold,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  subtleLinkText: {
    color: authColors.hint,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  pill: {
    alignSelf: 'flex-start',
    backgroundColor: authColors.primarySoft,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  pillText: {
    color: colors.gold,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 12,
    textAlign: 'center',
  },
});
