import { Platform, StyleSheet } from 'react-native';

export const authColors = {
  background: '#f6efe5',
  card: '#fffaf4',
  cardBorder: '#eadfce',
  surface: '#f2ebdf',
  primary: '#0f4f30',
  primarySoft: '#dceee3',
  text: '#143626',
  muted: '#5f6f64',
  hint: '#7f8c84',
  white: '#ffffff',
};

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: authColors.background,
    direction: 'rtl',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 32,
    gap: 16,
    direction: 'rtl',
  },
  hero: {
    paddingTop: 20,
    gap: 6,
    direction: 'rtl',
    alignItems: 'flex-end',
  },
  eyebrow: {
    color: authColors.primary,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 12,
    textAlign: 'left',
    writingDirection: 'rtl',
    alignSelf: 'flex-start',
  },
  title: {
    color: authColors.text,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 24,
    textAlign: 'left',
    writingDirection: 'rtl',
    lineHeight: 38,
    alignSelf: 'stretch',
    width: '100%',
  },
  subtitle: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    fontSize: 14,
    textAlign: 'left',
    writingDirection: 'rtl',
    lineHeight: 24,
    alignSelf: 'stretch',
    width: '100%',
  },
  card: {
    backgroundColor: authColors.card,
    borderColor: authColors.cardBorder,
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 12,
    shadowColor: '#1d2a22',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: Platform.OS === 'android' ? 2 : 0,
    direction: 'rtl',
    alignItems: 'stretch',
  },
  sectionTitle: {
    color: authColors.primary,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 14,
    textAlign: 'right',
    writingDirection: 'rtl',
    alignSelf: 'flex-start',
  },
  sectionHint: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
    lineHeight: 22,
    alignSelf: 'stretch',
    width: '100%',
  },
  field: {
    backgroundColor: authColors.surface,
    borderColor: authColors.cardBorder,
    borderRadius: 16,
    borderWidth: 1,
    color: authColors.text,
    paddingHorizontal: 14,
    paddingVertical: 14,
    textAlign: 'right',
    writingDirection: 'rtl',
    direction: 'rtl',
  },
  optionCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    direction: 'rtl',
  },
  optionTitle: {
    color: authColors.primary,
    fontFamily: 'NotoKufiArabic-Bold',
    textAlign: 'right',
    writingDirection: 'rtl',
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  optionDescription: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'right',
    writingDirection: 'rtl',
    lineHeight: 22,
    alignSelf: 'stretch',
    width: '100%',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: authColors.primary,
    borderRadius: 16,
    paddingVertical: 15,
    shadowColor: '#0f4f30',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: Platform.OS === 'android' ? 2 : 0,
    direction: 'rtl',
  },
  primaryButtonText: {
    color: authColors.white,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 15,
  },
  centerText: {
    color: authColors.muted,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'center',
    writingDirection: 'rtl',
    lineHeight: 24,
  },
  actionLink: {
    alignItems: 'center',
  },
  actionLinkText: {
    color: authColors.primary,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  subtleLinkText: {
    color: authColors.hint,
    fontFamily: 'NotoKufiArabic-Regular',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  pill: {
    alignSelf: 'flex-start',
    backgroundColor: authColors.primarySoft,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  pillText: {
    color: authColors.primary,
    fontFamily: 'NotoKufiArabic-Bold',
    fontSize: 12,
    textAlign: 'center',
  },
});
